


<GeneralShiftHolder>:
    general_shift_grid: general_shift_grid
    orientation: "vertical"
    ScrollView:
        size: self.size
        GridLayout:
            id: general_shift_grid
            col_default_width: dp(20)
            row_default_height: dp(20)
            cols: len(root.month_days)
            size_hint_y: None
            height: self.minimum_height


<MainLayout>:
    orientation: "vertical"
    Label:
        text: "Detailed shift"
        size_hint_y: .1



        